### ISSUE TITLE
Fractions are sent to PT using comma's as decimal separator

### ISSUE THREAD

**Issue by Amelsfort** [PTMagicians/PTMagic#227] opened 2020-12-15 13:07 UTC
**Describe the bug**
I noticed that my PT-settings show a 'buy_trailing_value' of '0,75' instead of '0.75'. The PT Magic settings also show the comma, but when I change it to '0.75' it gets translated to '75' or converted back to '0,75' again.

**To Reproduce**
1. Go to 'Settings - Analyzer'
2. Change one of the settings to a number using decimals
3. Save
4. Reload the page or check ProfitTrailer.

**Expected behavior**
PT Magic should use a point as a decimal separator everywhere or at least send it to Profit Trailer correctly.

**Desktop (please complete the following information):**
 - OS: Windows Server 2016
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22]: 87.0.4280.99

**Comment by HojouFotytu** [comment] 2020-12-15 15:03
Heya @Amelsfort,

Could you do me a favor and try editing your analyzer settings directly, via the settings.analyzer.json file, rather than via the web interface?  I have a feeling the problem might be the code grabbing values via the webpage. 

Please let me know -- thanks!

**Comment by PTdude** [comment] 2021-01-04 13:02
Until the problem is fixed in PTM, users in regions where a comma is used for a decimal can go to their "Region" settings in the windows control panel, "Additional Settings..."  then "Currency" tab, and select a period to use as a "decimal symbol"

**Comment by HojouFotytu** [comment] 2021-01-04 13:05
Until the problem is fixed in PTM, users in regions where a comma is used for a decimal can go to their "Region" settings in the windows control panel, "Additional Settings..."  then "Currency" tab, and select a period to use as a "decimal symbol"

**Comment by HojouFotytu** [comment] 2021-05-13 14:48
Seems the problem only occurs when editing via the GUI.
![image](https://user-images.githubusercontent.com/36724681/118142651-87dbbc80-b445-11eb-8c94-a28c6a50ceea.png)

**Closed** 2023-07-01 10:35 UTC
Labels: In Review, Waiting for User
